### ISSUE TITLE
Erreur : « Le format de la chaîne  d'entrée est incorrect. »

### ISSUE THREAD

**Issue by Owned67** [gus33000/ESD-Decrypter#8]
C:\ESD-Decrypter-master\ESD-Decrypter-master\bin\
ESDDecrypter.ps1 : Impossible de traiter la transformation d'argument sur le pa
ramètre « Scheme ». Impossible de convertir la valeur « E:\Image_7\Windows10\so
urces\install.esd » en type « System.Int32 ». Erreur : « Le format de la chaîne
 d'entrée est incorrect. »
    + CategoryInfo          : InvalidData: (:) [ESDDecrypter.ps1], ParentConta
   insErrorRecordException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,ESDDecrypte
   r.ps1

**Comment by gus33000** [comment]
D'après ce message, apparement vous avez specifié un fichier esd à la place d'un scheme. Voici une commande example pour vous aidez:

-ESD "esdfilepathgoeshere" -Destination = "destionationgoeshere" -CryptoKey "cryptokeygoeshere" -extensiontype "WIM" -scheme 1

Je ferme ce ticket, et je le reouvrirait si il y a un problème supplémentaire.
